apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml
  - frontend-configmap.yaml
  - frontend-ingress.yaml

commonLabels:
  app.kubernetes.io/name: compliance-classifier
  app.kubernetes.io/part-of: compliance-classifier-system