apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: compliance-classifier-production

commonLabels:
  environment: production

patches:
  - path: patches/frontend-deployment.yaml
  - path: patches/frontend-configmap.yaml
  - path: patches/frontend-ingress.yaml

configMapGenerator:
  - name: frontend-config
    behavior: merge
    literals:
      - api-url=http://api-service.compliance-classifier-production.svc.cluster.local:5000

images:
  - name: ${DOCKER_REGISTRY}/compliance-classifier-frontend
    newName: ${DOCKER_REGISTRY}/compliance-classifier-frontend
    newTag: production