apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false
    jsonData:
      timeInterval: 15s
      queryTimeout: 60s
      httpMethod: POST

  - name: Elasticsearch
    type: elasticsearch
    access: proxy
    url: http://elasticsearch:9200
    database: "[logstash-]YYYY.MM.DD"
    isDefault: false
    editable: false
    jsonData:
      timeField: "@timestamp"
      esVersion: 8.0.0
      maxConcurrentShardRequests: 5
      logMessageField: message
      logLevelField: level