name: Branch Protection Rules

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'  # Run weekly on Sunday at midnight

jobs:
  set-branch-protection:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set branch protection rules
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.ADMIN_TOKEN }}
        script: |
          const owner = context.repo.owner;
          const repo = context.repo.repo;
          
          // Main branch protection
          await github.rest.repos.updateBranchProtection({
            owner,
            repo,
            branch: 'main',
            required_status_checks: {
              strict: true,
              contexts: [
                'build-and-test',
                'security-scan',
                'e2e-tests',
                'build-docker-image'
              ]
            },
            enforce_admins: true,
            required_pull_request_reviews: {
              dismissal_restrictions: {},
              dismiss_stale_reviews: true,
              require_code_owner_reviews: true,
              required_approving_review_count: 2
            },
            restrictions: null,
            required_linear_history: true,
            allow_force_pushes: false,
            allow_deletions: false
          });
          
          console.log('Main branch protection rules set successfully');
          
          // Develop branch protection
          await github.rest.repos.updateBranchProtection({
            owner,
            repo,
            branch: 'develop',
            required_status_checks: {
              strict: true,
              contexts: [
                'build-and-test',
                'security-scan',
                'e2e-tests'
              ]
            },
            enforce_admins: false,
            required_pull_request_reviews: {
              dismissal_restrictions: {},
              dismiss_stale_reviews: true,
              require_code_owner_reviews: true,
              required_approving_review_count: 1
            },
            restrictions: null,
            required_linear_history: true,
            allow_force_pushes: false,
            allow_deletions: false
          });
          
          console.log('Develop branch protection rules set successfully');