http.host: "0.0.0.0"
xpack.monitoring.enabled: true
xpack.monitoring.elasticsearch.hosts: ["http://elasticsearch:9200"]
xpack.monitoring.elasticsearch.username: "${ELASTICSEARCH_USER}"
xpack.monitoring.elasticsearch.password: "${ELASTICSEARCH_PASSWORD}"
path.config: /usr/share/logstash/pipeline
config.reload.automatic: true
config.reload.interval: 30s
queue.type: persisted
queue.max_bytes: 1gb