apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
data:
  environment: "production"
  api-url: "http://api-service.compliance-classifier-production.svc.cluster.local:5000"
  feature-flags: '{"enableDebugMode": false, "enableBetaFeatures": false}'
  cache-control: "max-age=3600"