apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
data:
  environment: "staging"
  api-url: "http://api-service.compliance-classifier-staging.svc.cluster.local:5000"
  feature-flags: '{"enableDebugMode": true, "enableBetaFeatures": true}'